apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prob1-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage