apiVersion: apps/v1
kind: Deployment
metadata:
  name: phase_3_deployment
  labels:
    app: phase_3
spec:
  replicas: 5
  selector:
    matchLabels:
      app: phase_3
  template:
    metadata:
      labels:
        app: phase_3
    spec:
      containers:
      - name: phase_3
        image: pad2003/phase_3:v1
        ports:
        - containerPort: 5040
---
apiVersion: v1
kind: Service
metadata:
  name: phase_3_service
spec:
  selector:
    app: phase_3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5040